package com.apicostanalytics.service;

import com.apicostanalytics.dto.UsageEventResponse;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.Instant;
import java.util.List;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class UsageJdbcRepository {
    private final JdbcTemplate jdbcTemplate;

    public UsageJdbcRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void createUsageTable() {
        jdbcTemplate.execute("""
                create table if not exists api_usage (
                    id bigint generated by default as identity primary key,
                    api_id bigint not null,
                    endpoint_id bigint not null,
                    user_id bigint not null,
                    provider varchar(120) not null,
                    model varchar(120) not null,
                    endpoint varchar(255) not null,
                    status_code int not null,
                    latency_ms bigint not null,
                    input_units bigint not null,
                    output_units bigint not null,
                    cost numeric(16,6) not null,
                    timestamp timestamp not null
                )
                """);
        jdbcTemplate.execute("create index if not exists idx_api_usage_timestamp on api_usage(timestamp)");
        jdbcTemplate.execute("create index if not exists idx_api_usage_provider on api_usage(provider)");
        jdbcTemplate.execute("create index if not exists idx_api_usage_endpoint on api_usage(endpoint)");
    }

    public void batchInsert(List<UsageEventResponse> events) {
        String sql = """
                insert into api_usage
                (api_id, endpoint_id, user_id, provider, model, endpoint, status_code, latency_ms, input_units, output_units, cost, timestamp)
                values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """;
        jdbcTemplate.batchUpdate(sql, new BatchPreparedStatementSetter() {
            @Override
            public void setValues(PreparedStatement ps, int i) throws java.sql.SQLException {
                UsageEventResponse event = events.get(i);
                ps.setLong(1, event.apiId());
                ps.setLong(2, event.endpointId());
                ps.setLong(3, event.userId());
                ps.setString(4, event.provider());
                ps.setString(5, event.model());
                ps.setString(6, event.endpoint());
                ps.setInt(7, event.statusCode());
                ps.setLong(8, event.latencyMs());
                ps.setLong(9, event.inputUnits());
                ps.setLong(10, event.outputUnits());
                ps.setBigDecimal(11, event.cost());
                ps.setObject(12, Timestamp.from(event.timestamp()), Types.TIMESTAMP);
            }

            @Override
            public int getBatchSize() {
                return events.size();
            }
        });
    }

    public List<UsageEventResponse> findRecent(int limit) {
        return jdbcTemplate.query("""
                select api_id, endpoint_id, user_id, provider, model, endpoint, status_code, latency_ms,
                       input_units, output_units, cost, timestamp
                from api_usage
                order by timestamp desc
                limit ?
                """, (rs, rowNum) -> new UsageEventResponse(
                rs.getLong("api_id"),
                rs.getLong("endpoint_id"),
                rs.getLong("user_id"),
                rs.getString("provider"),
                rs.getString("model"),
                rs.getString("endpoint"),
                rs.getInt("status_code"),
                rs.getLong("latency_ms"),
                rs.getLong("input_units"),
                rs.getLong("output_units"),
                rs.getBigDecimal("cost"),
                rs.getTimestamp("timestamp").toInstant()), limit);
    }

    public Instant latestTimestamp() {
        return jdbcTemplate.queryForObject("select coalesce(max(timestamp), current_timestamp) from api_usage", Instant.class);
    }
}
